<a href="https://colab.research.google.com/github/bushragit/Machine-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy Array
NumPy is a powerful Python library used for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.  

In [ ]:
# Pandas is designed for working with tabular or heterogeneous data.
# NumPy, by contrast, is best suited for working with homogeneous numerical array data.


In [ ]:
import numpy as np

In [ ]:
a = np.zeros(9)
a
print(a.shape)
print(a.ndim)

(9,)
1


In [ ]:
b = np.zeros((9))
b.shape
print(b.shape)

(9,)


In [ ]:
c=np.zeros((3,3))
c
print(c.shape)
print(c.ndim)

(3, 3)
2


In [ ]:
d=np.zeros((3,3,3))
print(d)
print(d.shape)
print(d.ndim)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
(3, 3, 3)
3


In [ ]:
a=np.array((2,3,))
b=np.zeros((2,3))
print(a)
print(a.ndim)
print(b)
print(b.ndim)

In [ ]:
e = np.arange(16)

In [ ]:
e[2:7]    #slicing in an array

array([2, 3, 4, 5, 6])

In [ ]:
f = np.array([[1,2,3],[7,8,9],[4,5,6]])
print(f)
print(f.shape)
print(f.ndim)

[[1 2 3]
 [7 8 9]
 [4 5 6]]
(3, 3)
2


In [ ]:
f = np.array([[1,2,3],[7,8,9],[4,5,6]])
f
print(f.shape)
print(f.ndim)

In [ ]:
g = np.array([[[1,2,3],[7,8,9],[4,5,6]]])
print(f)
print(g.shape)
print(g.ndim)

[[[1 2 3]
  [7 8 9]
  [4 5 6]]]
(1, 3, 3)
3


In [ ]:
g = np.array([[[1,2,3],[7,8,9],[4,5,6]]])
print(g)
print(g.shape)
print(g.ndim)

[[[1 2 3]
  [7 8 9]
  [4 5 6]]]
(1, 3, 3)
3


In [ ]:
# vstack is a function that stacks arrays vertically (row-wise)
# hstack is a function that stacks arrays horizontally (column-wise)

In [ ]:
h = np.array([[[1,2,3],[7,8,9],[4,5,6]],[[1,2,3],[7,8,9],[4,5,6]]])
print(h)
print(h.shape)
print(h.ndim)

[[[1 2 3]
  [7 8 9]
  [4 5 6]]

 [[1 2 3]
  [7 8 9]
  [4 5 6]]]
(2, 3, 3)
3


In [ ]:
i = np.array([[[1,2,3],[7,8,9],[4,5,6]],[[1,2,3],[7,8,9],[4,5,6]],[[1,2,3],[7,8,9],[4,5,6]]])
print(i)
print(i.shape)
print(i.ndim)

[[[1 2 3]
  [7 8 9]
  [4 5 6]]

 [[1 2 3]
  [7 8 9]
  [4 5 6]]

 [[1 2 3]
  [7 8 9]
  [4 5 6]]]
(3, 3, 3)
3


In [ ]:
j = i.reshape(9,3)
j
print(j.shape)
print(j.ndim)

(9, 3)
2


In [ ]:
j.T

array([[1, 7, 4, 1, 7, 4, 1, 7, 4],
       [2, 8, 5, 2, 8, 5, 2, 8, 5],
       [3, 9, 6, 3, 9, 6, 3, 9, 6]])

In [ ]:
j = i.reshape(9,3,1)
print(j)
print(j.shape)
print(j.ndim)

In [ ]:
j = i.reshape(1,3,9)
print(j)
print(j.shape)
print(j.ndim)

[[[1 2 3 7 8 9 4 5 6]
  [1 2 3 7 8 9 4 5 6]
  [1 2 3 7 8 9 4 5 6]]]
(1, 3, 9)
3


In [ ]:
i
i.ndim
i.shape
i.size

(3, 3, 3)

In [ ]:
j
j.ndim
j.shape


(1, 3, 9)

In [ ]:
k = i.reshape(3,3,3)

In [ ]:
l = np.concatenate((i,k), axis = 1)
print(l)

[[[1 2 3]
  [7 8 9]
  [4 5 6]
  [1 2 3]
  [7 8 9]
  [4 5 6]]

 [[1 2 3]
  [7 6 9]
  [4 5 6]
  [1 2 3]
  [7 8 9]
  [4 5 6]]

 [[1 2 3]
  [7 8 9]
  [4 5 6]
  [1 2 3]
  [7 8 9]
  [4 5 6]]]


In [ ]:
h = l.flatten()
h

array([1, 2, 3, 7, 8, 9, 4, 5, 6, 1, 2, 3, 7, 8, 9, 4, 5, 6, 1, 2, 3, 6,
       6, 6, 6, 5, 6, 6, 2, 6, 6, 8, 6, 6, 5, 6, 1, 2, 3, 6, 8, 6, 6, 5,
       6, 6, 2, 6, 6, 8, 6, 6, 5, 6])

In [ ]:
np.hstack(i)

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [7, 8, 9, 7, 8, 9, 7, 8, 9],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [ ]:
np.vstack(i)

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6],
       [1, 2, 3],
       [7, 8, 9],
       [4, 5, 6],
       [1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [ ]:
np.full([2,3], 44)

NameError: name 'np' is not defined

In [ ]:
df[‘student_cat’] = np.where(df[‘score’] > 80, ‘good’, ‘bad’)

In [ ]:
import numpy as np
#array >30
arr = np.array([[10, 15, 20, 25],
                  [30, 35, 40, 45],
                  [50, 55, 60, 65]])

In [ ]:
# arr = np.where(arr > 30, "good" "bad")
# arr

ValueError: either both or neither of x and y should be given

In [ ]:
arr[1:,:]

array([[30, 35, 40, 45],
       [50, 55, 60, 65]])

In [ ]:
condition = arr > 30
condition

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
arr[arr>30]

array([35, 40, 45, 50, 55, 60, 65])

In [ ]:
# Importing Numpy module
import numpy as np

# Creating a 2-D Numpy array
n_arr = np.array([[45.42436315, 52.48558583, 10.32924763],
                  [5.7439979, 50.58220701, 25.38213418]])
print("Given array:")
print(n_arr)

print("\nReplace all elements of array which are greater than 30. to 5.25")
n_arr[n_arr>30]=5.25
n_arr

Given array:
[[45.42436315 52.48558583 10.32924763]
 [ 5.7439979  50.58220701 25.38213418]]

Replace all elements of array which are greater than 30. to 5.25


array([[ 5.25      ,  5.25      , 10.32924763],
       [ 5.7439979 ,  5.25      , 25.38213418]])

In [ ]:
n_arr = np.array([[[11, 25.5, 70.6], [30.9, 45.5, 55.9], [20.7, 45.8, 7.1]],
                  [[50.1, 65.9, 8.2], [70.4, 85.8, 10.3], [11.3, 22.2, 33.6]],
                  [[19.9, 69.7, 36.8], [1.2, 5.1, 24.4], [4.9, 20.8, 96.7]]])

print("Given array:")
print(n_arr)

print("\nReplace all elements of array which are less than 10 to Nan")
n_arr[n_arr < 10.] = np.nan

print("New array :\n")
print(n_arr)

NameError: name 'np' is not defined

In [ ]:
# Importing Numpy module
import numpy as np

# Creating a 2-D Numpy array
n_arr = np.array([[45, 52, 10],
                  [1, 5, 25]])

print("Given array:")
print(n_arr)

#print("\nReplace all elements of array which are \ greater than or equal to 25 to 0")

n_arr[n_arr>=25]=0
n_arr

Given array:
[[45 52 10]
 [ 1  5 25]]


array([[ 0,  0, 10],
       [ 1,  5,  0]])

In [ ]:
# https://www.geeksforgeeks.org/python-numpy-practice-exercises-questions-and-solutions (for practice)

In [ ]:
print(n_arr*2)
print(n_arr-2)
print(n_arr+2)
print(n_arr/2)

[[ 0  0 20]
 [ 2 10  0]]
[[-2 -2  8]
 [-1  3 -2]]
[[ 2  2 12]
 [ 3  7  2]]
[[0.  0.  5. ]
 [0.5 2.5 0. ]]


In [ ]:
a = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
b = np.array([0, 2,3])

In [ ]:
a*b

array([[ 0,  4,  9],
       [ 0,  8, 15],
       [ 0,  4,  9]])

In [ ]:
n_arr = np.array([[[11, 25.5, 70.6], [30.9, 45.5, 55.9], [20.7, 45.8, 7.1]],
                  [[50.1, 65.9, 8.2], [70.4, 85.8, 10.3], [11.3, 22.2, 33.6]],
                  [[19.9, 69.7, 36.8], [1.2, 5.1, 24.4], [4.9, 20.8, 96.7]]])

In [ ]:
n_arr

array([[[11. , 25.5, 70.6],
        [30.9, 45.5, 55.9],
        [20.7, 45.8,  7.1]],

       [[50.1, 65.9,  8.2],
        [70.4, 85.8, 10.3],
        [11.3, 22.2, 33.6]],

       [[19.9, 69.7, 36.8],
        [ 1.2,  5.1, 24.4],
        [ 4.9, 20.8, 96.7]]])

In [ ]:
n_arr*b

array([[[  0. ,  51. , 211.8],
        [  0. ,  91. , 167.7],
        [  0. ,  91.6,  21.3]],

       [[  0. , 131.8,  24.6],
        [  0. , 171.6,  30.9],
        [  0. ,  44.4, 100.8]],

       [[  0. , 139.4, 110.4],
        [  0. ,  10.2,  73.2],
        [  0. ,  41.6, 290.1]]])

matrix multiplication in NumPy (or any linear algebra), the number of columns in the first matrix should be equal to the number of rows in the second matrix.

In other words, if you have two matrices:

Matrix A of shape (m, n) (m rows, n columns)
Matrix B of shape (p, q) (p rows, q columns)
For matrix multiplication (A @ B) to be valid, the number of columns in A (which is n) must equal the number of rows in B (which is p). The resulting matrix will have a shape of (m, q). [CR]

So, in mathematical terms:

n == p
The result will be a matrix of shape (m, q).
Let me know if you'd like an example!

In [ ]:
# Define matrix A (2x3)
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Define matrix B (3x2)
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

# Multiply matrices A and B
C = np.dot(A, B)

In [ ]:
C

array([[ 58,  64],
       [139, 154]])

In [ ]:
arr = np.random.randn(10,10)
print(arr)
arr1 = np.round(arr,2)
print(arr1)

[[ 0.48795972 -1.03233534  0.19343966 -1.63099642 -1.18776572 -0.20562511
   0.99665309 -0.14242675  0.14238564  0.4418926 ]
 [ 0.99755281  0.62559799 -0.94552329 -0.61502226 -1.05700729 -0.73248235
   0.57020804 -1.19524322 -0.34599365 -0.70165727]
 [ 0.97658676  0.39458385 -2.51559372  1.08588252  0.26642115  0.29713886
  -1.07009026  0.85550623  1.37011855  0.35889208]
 [-0.4102191   0.79181185  0.43249978 -0.19106725 -0.11886778  0.69888801
   1.33118737  1.60885706  1.11192052  1.61281363]
 [-0.78010794  0.40022844  0.49735602  0.31233926 -1.01117175 -0.72221642
  -2.16685217 -0.20199927  0.25145866  0.60561417]
 [-1.90233181 -0.82082225 -0.32439868 -0.44339879 -0.83819225  0.06890289
   1.90690395  0.60252869 -0.72360148  0.72256252]
 [-0.91286847  1.26522298  0.03745491  0.18192798  0.58042146  0.87158036
  -0.75647535 -0.42627315  0.68077371  0.08136865]
 [-0.40985894 -0.54451399 -0.05478881  1.60355102  0.27205611  1.08119242
  -0.39960331 -0.42612836 -0.58522716  0.11805033]


In [ ]:
print(arr1[1:10:2,::]) #selects all columns sam as :  print(arr1[1:10:2,::])   print(arr1[1:10:2,::])

[[ 1.    0.63 -0.95 -0.62 -1.06 -0.73  0.57 -1.2  -0.35 -0.7 ]
 [-0.41  0.79  0.43 -0.19 -0.12  0.7   1.33  1.61  1.11  1.61]
 [-1.9  -0.82 -0.32 -0.44 -0.84  0.07  1.91  0.6  -0.72  0.72]
 [-0.41 -0.54 -0.05  1.6   0.27  1.08 -0.4  -0.43 -0.59  0.12]
 [ 0.09 -0.85 -0.89  0.57 -1.83  0.8  -1.25  0.19  0.86 -1.51]]


In [ ]:
print(arr1[1:10:2,::])

[[ 1.    0.63 -0.95 -0.62 -1.06 -0.73  0.57 -1.2  -0.35 -0.7 ]
 [-0.41  0.79  0.43 -0.19 -0.12  0.7   1.33  1.61  1.11  1.61]
 [-1.9  -0.82 -0.32 -0.44 -0.84  0.07  1.91  0.6  -0.72  0.72]
 [-0.41 -0.54 -0.05  1.6   0.27  1.08 -0.4  -0.43 -0.59  0.12]
 [ 0.09 -0.85 -0.89  0.57 -1.83  0.8  -1.25  0.19  0.86 -1.51]]


In [ ]:
print(arr1[1:10:2,::])

[[ 1.    0.63 -0.95 -0.62 -1.06 -0.73  0.57 -1.2  -0.35 -0.7 ]
 [-0.41  0.79  0.43 -0.19 -0.12  0.7   1.33  1.61  1.11  1.61]
 [-1.9  -0.82 -0.32 -0.44 -0.84  0.07  1.91  0.6  -0.72  0.72]
 [-0.41 -0.54 -0.05  1.6   0.27  1.08 -0.4  -0.43 -0.59  0.12]
 [ 0.09 -0.85 -0.89  0.57 -1.83  0.8  -1.25  0.19  0.86 -1.51]]


This selects rows starting from index 1 (second row).
Stops before index 10.
Skips every second row (i.e., it takes row 1, skips row 2, takes row 3, skips row 4, and so on)

In [ ]:
data = np.array([['cat', 'dog', 'cat'],['dog','dog','cat'],['cat','cat','dog']])
data

array([['cat', 'dog', 'cat'],
       ['dog', 'dog', 'cat'],
       ['cat', 'cat', 'dog']], dtype='<U3')

In [ ]:
type(data)

numpy.ndarray

In [ ]:
data == "cat"

array([[ True, False,  True],
       [False, False,  True],
       [ True,  True, False]])

In [ ]:
values = np.random.randn(3,3)
values

array([[-0.33299459, -0.94750881,  1.03053517],
       [ 0.38496291,  1.44086939, -0.1800066 ],
       [-2.43398188,  0.6853886 , -0.30583817]])

In [ ]:
values[data == "cat"]

array([-0.33299459,  1.03053517, -0.1800066 , -2.43398188,  0.6853886 ])

In [ ]:
subjects = np.array(['math', 'science', 'math', 'english', 'math'])
scores = np.array([85, 90, 78, 88, 92])
# Create a mask for subjects that are 'math'
mask = (subjects == 'math')

# Increase scores for 'math' students by 5
scores[mask] += 5

print(scores)


[90 90 83 88 97]


In [ ]:
scores[2]+2

85

In [ ]:
subjects = np.concatenate((subjects, ['geography']))
subjects = np.append(subjects, 'geography')
subjects

array(['math', 'science', 'math', 'english', 'math', 'geography',
       'geography', 'geography', 'geography'], dtype='<U9')

In [ ]:
import numpy as np

# Existing subjects array
subjects = np.array(['math', 'science', 'math', 'english', 'math'])

# Remove 'science' by creating a mask
subjects = subjects[subjects != 'science']

print(subjects)

['math' 'math' 'english' 'math']


In [ ]:
#replace by indexing
subjects[0]="science"

In [ ]:
subjects

array(['science', 'math', 'english', 'math'], dtype='<U7')

In [ ]:
subject = subjects[:-1]
subject

array(['science', 'math', 'english'], dtype='<U7')

In [ ]:
subject = subjects[-1]
subject

'math'

In [ ]:
array_b = ['product', 'loan', 4000]
for idx, ele in enumerate(array_b):
    print(idx, ele)

0 product
1 loan
2 4000


In [ ]:
array_b

['product', 'loan', 4000]

In [ ]:
array_b[2]=str(array_b[2])

In [ ]:
array_b

['product', 'loan', '4000']